apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" 
  volumeName: ebs-static-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi