kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: expense
  name: frontend
  labels:
    purpose: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: frontend
  template:
    metadata:
      labels:
        purpose: frontend
    spec:
      containers:
      - name: frontend
        image: chadcoderchandan/frontend:v2 
        # in the above image we made a change in nginx.conf, default nginx port 80 to 8080 because 
        # k-8 cannot open ports from 1-1024(only allowed for root users) for non-root users.
        # but we have given non root user in image. 
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  selector:
    purpose: frontend
  ports:
    - protocol: TCP
      port: 80  
      # why 80 and why not 8080??
      # so that we dont have to give :8080 after loadbalacer endpoint(like lb-endpoint:8080)  
      targetPort: 8080
