apiVersion: v1
kind: Pod
metadata:
  name: podname
  namespace: expense
  #if we doesn't specify namespace, resource(pod in this case) will be created in default namespace
spec:
  containers:
  - name: container1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
