apiVersion: v1
kind: Pod
metadata:
  name: PodWithMutlipleContainers
spec:
  containers:
  - name: container1
    image: nginx

  - name: container2
    image: almalinux:9
    command: ["sleep","1000"]
