apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multi-containers
spec:
  containers:
  - name: container1
    image: nginx

  - name: container2
    image: almalinux:9
    command: ["sleep","1000"]


    # how to swith between containers within pod,
    # "kubectl exec -it <pod-name> -c <conatiner-name> -- bash"
