apiVersion: v1
kind: Pod
metadata: 
  name: config-map-demo
spec:
  containers:
    - name: container1
      image: nginx
      envFrom:
        - configMapRef:
            name: myconfig  # myconfig --> name of "ConfigMap" created in 08-config-map.yaml.

