apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: Y2hhbmRhbgo=  # base64 of "chandan"
  password: Y2hhbjEyMwo=  #base64 of "chan123"


  # echo "chandan" | base64 ==> "Y2hhbmRhbgo="  
  # echo "Y2hhbmRhbgo=" | base64 -d ==> "chandan"