apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: container1
      image: nginx
      envFrom:
        - secretRef:
            name: mysecret

      # or

      # env:
      #   - name: username
      #     valueFrom:
      #       secretKeyRef:
      #         name: mysecret
      #         key: username

      #   - name: password
      #     valueFrom:
      #       secretKeyRef:
      #         name: mysecret
      #         key: password