apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector:  # this is how we attach service to every pod, where labels should match.
    environment: production
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # service port
      # targetPort: 80 
       # port on which target app is running. we dont have to give this, if container port is given in pod.


---

apiVersion: v1
kind: Pod
metadata:
  name: service-demo-pod
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80