apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
spec:
  type: NodePort  
  selector:
    purpose: nodeport-demo-pod
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007          # range-->30000-32767 


---

apiVersion: v1
kind: Pod
metadata:
  name: nodeport-demo-pod
  labels:
    purpose: nodeport-demo-pod
spec:
  containers:
  - name: nginx
    image: nginx
   