# LoadBalancer: Automatically provisions an external load balancer(based on cloud provider using
# -->aws in our case) to expose a service to external traffic with load balancing.

# how it works?
# lb --> ip:nodePort --> cluster-ip of the service --> pods attached to that service based on selectors.


apiVersion: v1
kind: Service
metadata:
  name: lb-demo
spec:
  type: LoadBalancer  
  selector:
    purpose: lb-demo-pod
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007      


---

apiVersion: v1
kind: Pod
metadata:
  name: lb-demo-pod
  labels:
    purpose: lb-demo-pod
spec:
  containers:
  - name: nginx
    image: nginx
   