apiVersion: v1
kind: Service
metadata:
  name: lb-demo
spec:
  type: LoadBalancer  
  selector:
    purpose: lb-demo-pod
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007      


---

apiVersion: v1
kind: Pod
metadata:
  name: lb-demo-pod
  labels:
    purpose: lb-demo-pod
spec:
  containers:
  - name: nginx
    image: nginx
   