 # "eksctl create cluster --config-file=eks.yaml" ==> create cluster

  # "eksctl delete cluster --config-file=eks.yaml" ==> delete cluster

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

managedNodeGroups:
- name: expense
  instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
  spot: true
  desiredCapacity: 3

#Cloud instances pricing models--> spot,reserved,on-demand

# on-demand --> used for unpredictable workloads, pay-as-you-go model, no long term commitment(so high price).
  # Eg: A food delivery app runs its servers on on-demand nodes to handle customer orders without downtime.

# reserved --> used for predictable workloads, fixed and low cost for long term commitment.
  # Eg:An online school hosts its learning platform on reserved nodes because students access it daily.

# spot --> used for non-critical tasks, no fixed resources as above two, so low cost
  # Eg: A video editing company uses spot nodes to render movies cheaply, even if some jobs get interrupted.

 


