kind: Pod
apiVersion: v1
metadata:
  name: init-cont-demo
spec:
  initContainers:
  - name: init-cont
    image: busybox:1.28   # busybox:1.28-->image for running commands 
    command: ['sh', '-c', "until nslookup google.com; do echo waiting for myservice; sleep 2; done"]
  # unless and untill "nslookup google.com" give response, the main container(below) doesn't run.
  containers:
  - name: cont-1
    image: nginx

# Usecase
# 1. Check whether mysql is running(using init container) before creating backend(in main container).
# 2. fetching secrets.
# 3. it decreases the load on main container.