kind: Pod
apiVersion: v1
metadata:
  name: init-cont-demo
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28   # image used to run small commands
    command: ['sh', '-c', "until nslookup googile.com; do echo waiting for google; sleep 2; done"]
  # cont-1 starts if and only if "nslookup google.com" is successful, if not it waits for 2 seconds and try nslookup again until its successful
  containers:
  - name: cont-1
    image: nginx