kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: expense
  name: mysql
  labels:
    purpose: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: mysql
  template:
    metadata:
      labels:
        purpose: mysql
    spec:
      containers:
      - name: mysql
        image: chadcoderchandan/mysql:v1
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    purpose: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
