apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---


apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    purpose: efs-app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim


---


apiVersion: v1
kind: Service
metadata:
  name: efs-app
spec:
  type: LoadBalancer  
  selector:
    purpose: efs-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007 