kind: Pod
apiVersion: v1
metadata:
  name: node-affinity-demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: yo
            operator: In
            values:
            - bro
            - bhai
    #  the above key value is set in node like
    #  kubectl label nodes <node-name> key=value 

    # removing label from node
    # kubectl label nodes <node-name> key- 

    # we can just use operator "In" for affinity and "NotIn" for anti-affinity 

    # if we are using "In" this means the node should have key with any one of the values.

    # if we are using "NotIn" this means the node should not have key or can have key
    # but different values other than mentioned values.

     # if we are using "Exists" or "DoesNotExist", we just have to give key and operator.
     # 


    
  containers:
  - name: node-affinity-demo
    image: nginx

