
# In this we dont have to attach any label to node

# pod-1 and pod-2 should not be in same node, so the creation of pod-2 is based on labels given
# in pod-1. we just have to use podAntiAffinity
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: pod-2
    image: nginx
