
# In this we dont have to attach any label to node

# pod-1 and pod-2 should not be in same node, so the creation of pod-2 is based on labels given
# in pod-1. we just have to use podAntiAffinity

apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone

# while using podAntiAffinity scheduler not only avoids the node on which pod with label app:pod-1 is
# scheduled, but also the topologyKey: zone or region or hostname(node name) is also considered.

# if we have given --> topologyKey: topology.kubernetes.io/zone
# Scheduler avoids scheduling pod on same node and zone.

# if we have given --> topologyKey: topology.kubernetes.io/region
# Scheduler avoids scheduling pod on same node and region.

# if we have given --> topologyKey: topology.kubernetes.io/hostname
# Scheduler avoids scheduling pod on same node which is same as hostname.

  containers:
  - name: pod-2
    image: nginx
