# kubectl taint nodes <node-name> key=value:NoSchedule
  #dont schedule pods if taints and tolerations are not matching.

# kubectl taint nodes <node-name> key=value:NoSchedule-
  # untaint a node


# kubectl taint nodes <node-name> key=value:NoExecute
 #dont schedule pods if taints and tolerations are not matching and also evict/remove already running 
 #pods.

kind: Pod
apiVersion: v1
metadata:
  name: taint-demo
spec:
  containers:
  - name: taint-demo
    image: nginx
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  tolerations:
  - key: "yo"
    operator: "Equal"
    value: "bro"
    effect: "NoSchedule"

  # The only node in the az us-east-1c is tainted
  # (i.e kubectl taint nodes <node-name-in-az-us-east-1> yo=bro:NoSchedule),
  #  pod will be scheduled only when the tolerations is given in pod definition.
  #  otherwise pod status will be in "Pending"
  
