apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::084828564374:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-QAJ9KKHkLXCA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::084828564374:user/suresh 
      username: suresh 
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: e137e450-1c7c-492c-a378-bd32fe22ba42
