apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::084828564374:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-ZpJJJJaDTeAk
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - pod-reader
      userarn: arn:aws:iam::084828564374:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 8363ff58-d6dc-4a39-8c96-0376552fd189
