apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" 
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d


---


apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer  
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 30007    