kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: expense
  name: backend
  labels:
    purpose: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: backend
  template:
    metadata:
      labels:
        purpose: backend
    spec:
      containers:
      - name: backend
        image: joindevops/backend:1.0.0
       

---

apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  selector:
    purpose: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
